//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLMTranslation.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLMTranslation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ApiKey 的本地化字符串。
        /// </summary>
        internal static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ApiKey obtained from the Zhipu AI API official website 的本地化字符串。
        /// </summary>
        internal static string ApiKey_Des {
            get {
                return ResourceManager.GetString("ApiKey_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete Translation Result 的本地化字符串。
        /// </summary>
        internal static string Complete_Translation {
            get {
                return ResourceManager.GetString("Complete_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explain 的本地化字符串。
        /// </summary>
        internal static string Explain {
            get {
                return ResourceManager.GetString("Explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Append target text explain 的本地化字符串。
        /// </summary>
        internal static string Explain_Des {
            get {
                return ResourceManager.GetString("Explain_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to get your ApiKey from the site and enter it in the extension settings. 的本地化字符串。
        /// </summary>
        internal static string GetApiKeyUrlInfo {
            get {
                return ResourceManager.GetString("GetApiKeyUrlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 glm-4.5-flash 的本地化字符串。
        /// </summary>
        internal static string Model_Default {
            get {
                return ResourceManager.GetString("Model_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zhipu AI Language ​Model Name 的本地化字符串。
        /// </summary>
        internal static string Model_Des {
            get {
                return ResourceManager.GetString("Model_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source_Language 的本地化字符串。
        /// </summary>
        internal static string Source_Language {
            get {
                return ResourceManager.GetString("Source_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string Source_Language_Default {
            get {
                return ResourceManager.GetString("Source_Language_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待翻译的源语言 的本地化字符串。
        /// </summary>
        internal static string Source_Language_Des {
            get {
                return ResourceManager.GetString("Source_Language_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpaceFinish 的本地化字符串。
        /// </summary>
        internal static string SpaceFinish {
            get {
                return ResourceManager.GetString("SpaceFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 true 的本地化字符串。
        /// </summary>
        internal static string SpaceFinish_Default {
            get {
                return ResourceManager.GetString("SpaceFinish_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press the spacebar to start searching to prevent unnecessary API requests 的本地化字符串。
        /// </summary>
        internal static string SpaceFinish_Des {
            get {
                return ResourceManager.GetString("SpaceFinish_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speech 的本地化字符串。
        /// </summary>
        internal static string Speech {
            get {
                return ResourceManager.GetString("Speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;role&quot;: &quot;You are a professional translation assistant, capable of accurately translating between {0} and {1}&quot;,
        ///  &quot;rqstd_title&quot;: &quot;Translation Requirements&quot;,
        ///  &quot;rqstd&quot;: [
        ///    &quot;Only return the translation result in JSON format, without adding any explanations, comments, or additional content.&quot;,
        ///    &quot;Maintain the tone and style of the original text.&quot;,
        ///    &quot;Ensure the translation is accurate, natural, and fluent.&quot;,
        ///    &quot;Do not add prefixes like &apos;Translation Result:&apos;.&quot;,
        ///    &quot;Directly output the transl [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SystemText {
            get {
                return ResourceManager.GetString("SystemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target_Language 的本地化字符串。
        /// </summary>
        internal static string Target_Language {
            get {
                return ResourceManager.GetString("Target_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string Target_Language_Default {
            get {
                return ResourceManager.GetString("Target_Language_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target language of the translation 的本地化字符串。
        /// </summary>
        internal static string Target_Language_Des {
            get {
                return ResourceManager.GetString("Target_Language_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target_Modes 的本地化字符串。
        /// </summary>
        internal static string Target_Modes {
            get {
                return ResourceManager.GetString("Target_Modes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 professional,concise 的本地化字符串。
        /// </summary>
        internal static string Target_Modes_Default {
            get {
                return ResourceManager.GetString("Target_Modes_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Separate translation types with commas to use them as prompts for the AI. 的本地化字符串。
        /// </summary>
        internal static string Target_Modes_Des {
            get {
                return ResourceManager.GetString("Target_Modes_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url 的本地化字符串。
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://open.bigmodel.cn/api/paas/v4/chat/completions 的本地化字符串。
        /// </summary>
        internal static string Url_Default {
            get {
                return ResourceManager.GetString("Url_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zhipu AI Api Url 的本地化字符串。
        /// </summary>
        internal static string Url_Des {
            get {
                return ResourceManager.GetString("Url_Des", resourceCulture);
            }
        }
    }
}
